### ISSUE TITLE
cannot import mobilenet_v2_FR_sz224

### ISSUE THREAD

**Issue by govindamagrawal** [tranluan/DR-GAN#1]
Hi,
I am trying to run the ropository. But I am not able to import mobilenet_v2_FR_sz224. Can you please specify a link where it can be  found. I tried seaching https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet/mobilenet_v2.py but mobilenet_v2_FR_sz224 was not present.

**Comment by samjcheng** [comment]
I got the same isssue

**Comment by tranluan** [comment]
Should be fixed now!
